/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramasRouteImport } from './routes/programas'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramasSlugRouteImport } from './routes/programas.$slug'

const ProgramasRoute = ProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasSlugRoute = ProgramasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/noticias': typeof NoticiasRoute
  '/programas': typeof ProgramasRouteWithChildren
  '/programas/$slug': typeof ProgramasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/noticias': typeof NoticiasRoute
  '/programas': typeof ProgramasRouteWithChildren
  '/programas/$slug': typeof ProgramasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/noticias': typeof NoticiasRoute
  '/programas': typeof ProgramasRouteWithChildren
  '/programas/$slug': typeof ProgramasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/galeria' | '/noticias' | '/programas' | '/programas/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/galeria' | '/noticias' | '/programas' | '/programas/$slug'
  id:
    | '__root__'
    | '/'
    | '/galeria'
    | '/noticias'
    | '/programas'
    | '/programas/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriaRoute: typeof GaleriaRoute
  NoticiasRoute: typeof NoticiasRoute
  ProgramasRoute: typeof ProgramasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programas': {
      id: '/programas'
      path: '/programas'
      fullPath: '/programas'
      preLoaderRoute: typeof ProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas/$slug': {
      id: '/programas/$slug'
      path: '/$slug'
      fullPath: '/programas/$slug'
      preLoaderRoute: typeof ProgramasSlugRouteImport
      parentRoute: typeof ProgramasRoute
    }
  }
}

interface ProgramasRouteChildren {
  ProgramasSlugRoute: typeof ProgramasSlugRoute
}

const ProgramasRouteChildren: ProgramasRouteChildren = {
  ProgramasSlugRoute: ProgramasSlugRoute,
}

const ProgramasRouteWithChildren = ProgramasRoute._addFileChildren(
  ProgramasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriaRoute: GaleriaRoute,
  NoticiasRoute: NoticiasRoute,
  ProgramasRoute: ProgramasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
